runtime: nodejs16

instance_class: F2

env_variables:
  bucket_name: superscan-gcs-bucket
  MONGODB_URI: "mongodb+srv://superscandev:superscandev06@superscan.ntiv5.mongodb.net/SuperScan?retryWrites=true&w=majority"
  PORT: 3000
  PORT_ALTERNATIVE: 3001
  TOKEN_SECRET_KEY: SUPERSCANDEV
